apiVersion: v1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 0
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: maheshmadmax/hellonode
        name: nodejs
        ports:
        - containerPort: 8000
          name: server
      restartPolicy: Always
status: {}

---
kind: Service
apiVersion: v1
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  externalIPs:
    - 172.31.6.247
